[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify configuration file for deployment
[build]
  publish = "dist"
  command = "bun run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
